// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfATirIUC7sNiEXc-QLJdoay1XsNYv56w',
    appId: '1:722376799583:web:9a4aa860cc74f915eef2ea',
    messagingSenderId: '722376799583',
    projectId: 'pay-mobile-ddab3',
    authDomain: 'pay-mobile-ddab3.firebaseapp.com',
    storageBucket: 'pay-mobile-ddab3.appspot.com',
    measurementId: 'G-C3S6G3P5KS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyNchM2NEz-4cernri4WZLJq7PJdzYhhw',
    appId: '1:722376799583:android:43a63325c4852c6deef2ea',
    messagingSenderId: '722376799583',
    projectId: 'pay-mobile-ddab3',
    storageBucket: 'pay-mobile-ddab3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKFSKfhaBZJAfLZwrphHnZMjz7yFR9urs',
    appId: '1:722376799583:ios:d5a7f4fabc06bc20eef2ea',
    messagingSenderId: '722376799583',
    projectId: 'pay-mobile-ddab3',
    storageBucket: 'pay-mobile-ddab3.appspot.com',
    iosClientId: '722376799583-bcaotvdv59pdcjld239n4msn193j3t02.apps.googleusercontent.com',
    iosBundleId: 'com.dayoniyi.peertopeermoneytransferapp',
  );
}
